/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cofftastictill;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17366481
 */
public class CofftasticTillGUI extends javax.swing.JFrame {

    Cofftastic c;
    ArrayList<Cofftastic> aList;
    String Customer;
    String Beverage;
    String cupSize;
    String registeredBy;
    int transID;
    String managerType;
    int coffcount;

    /**
     * Creates new form CofftasticTillGUI
     */
    public CofftasticTillGUI() {
        initComponents();

        aList = new ArrayList<>();
        coffcount = 0;

        //  comboBox = new JComboBox(items);
        cusNameLbl.setVisible(false);
        cusNameTf.setVisible(false);
        transidLbl.setVisible(false);
        transidTf.setVisible(false);
        regbyTf.setVisible(false);
        regbyLbl.setVisible(false);
        beverageLbl.setVisible(false);
        beverageCmb.setVisible(false);
        cupsizeLbl.setVisible(false);
        cupsizeCmb.setVisible(false);
        addBtn.setVisible(false);
        displayBtn.setVisible(false);
        searchTID.setVisible(false);
        deleteBtn.setVisible(false);
        viewsavedBtn.setVisible(false);
        manTypeCmb.setVisible(false);
        manTypeLbl.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cusNameLbl = new javax.swing.JLabel();
        transidLbl = new javax.swing.JLabel();
        beverageLbl = new javax.swing.JLabel();
        beverageCmb = new javax.swing.JComboBox<>();
        cupsizeLbl = new javax.swing.JLabel();
        cupsizeCmb = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchTID = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        fsBtn = new javax.swing.JButton();
        manBtn = new javax.swing.JButton();
        commentBtn = new javax.swing.JButton();
        transidTf = new javax.swing.JTextField();
        regbyLbl = new javax.swing.JLabel();
        cusNameTf = new javax.swing.JTextField();
        regbyTf = new javax.swing.JTextField();
        viewsavedBtn = new javax.swing.JButton();
        manTypeCmb = new javax.swing.JComboBox<>();
        manTypeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cofftastictill/cofftasticImage.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        cusNameLbl.setText("Customer");

        transidLbl.setText("Transaction ID");

        beverageLbl.setText("Beverage");

        beverageCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coffee", "Tea", "Latte", "Water" }));
        beverageCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beverageCmbActionPerformed(evt);
            }
        });

        cupsizeLbl.setText("Cup Size");

        cupsizeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL" }));
        cupsizeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupsizeCmbActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD DETAILS");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setBackground(new java.awt.Color(0, 0, 0));
        displayBtn.setForeground(new java.awt.Color(255, 255, 255));
        displayBtn.setText("DISPLAY DETAILS");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchTID.setBackground(new java.awt.Color(0, 0, 0));
        searchTID.setForeground(new java.awt.Color(255, 255, 255));
        searchTID.setText("Search By Customer Name");
        searchTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTIDActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE ALL DETAILS");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        fsBtn.setBackground(new java.awt.Color(0, 0, 0));
        fsBtn.setForeground(new java.awt.Color(255, 255, 255));
        fsBtn.setText("FLOOR STAFF");
        fsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsBtnActionPerformed(evt);
            }
        });

        manBtn.setBackground(new java.awt.Color(0, 0, 0));
        manBtn.setForeground(new java.awt.Color(255, 255, 255));
        manBtn.setText("MANAGER");
        manBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manBtnActionPerformed(evt);
            }
        });

        commentBtn.setBackground(new java.awt.Color(0, 0, 0));
        commentBtn.setForeground(new java.awt.Color(255, 255, 255));
        commentBtn.setText("COMMENT");
        commentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentBtnActionPerformed(evt);
            }
        });

        regbyLbl.setText("Till Operator");

        regbyTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbyTfActionPerformed(evt);
            }
        });

        viewsavedBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewsavedBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewsavedBtn.setText("VIew Saved Details");
        viewsavedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsavedBtnActionPerformed(evt);
            }
        });

        manTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head Manager", "Assistant Manager", "Supervisor", "Floor Manager" }));
        manTypeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manTypeCmbActionPerformed(evt);
            }
        });

        manTypeLbl.setText("Manager Position");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regbyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manTypeLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manTypeCmb, 0, 0, Short.MAX_VALUE)
                            .addComponent(cusNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(regbyTf)
                            .addComponent(transidTf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beverageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beverageCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cupsizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cupsizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(commentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewsavedBtn)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cusNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(beverageCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(beverageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cusNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regbyTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cupsizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cupsizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manTypeCmb)
                    .addComponent(manTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewsavedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beverageCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beverageCmbActionPerformed
        // TODO add your handling code here:

        /*     beverageCmb.addItemListener(new ItemListener() {
        @Override
        public void itemStateChanged(ItemEvent e) {
            //perform here your database querys for specific items.
            String value = String.valueOf(beverageCmb.getSelectedItem().toString());
  System.out.println("value selected: "+value);
           /*if(e.getItem().equals(items[0]) && e.getStateChange() == ItemEvent.SELECTED) {
                //db query for it "IT1"
                  String v =String.valueOf(beverageCmb.getSelectedItem().toString());
        System.out.println("value selected: "+v);
            }
        }

    });*/

    }//GEN-LAST:event_beverageCmbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (c instanceof CofftasticEmployee) {
            c = new CofftasticEmployee();

            Customer = cusNameTf.getText();
            // cupSize = cupsizeCmb.getText(); /// GET WORKING ON WED
            //  Beverage = beverageCmb.getText(); /// GET WORKING ON WED
            registeredBy = regbyTf.getText();

            c.setCustomer(Customer);
            c.setCupSize(cupSize);
            c.setBeverage(Beverage);
            ((CofftasticEmployee) c).setRegisteredBy(registeredBy);
            cupSize = cupsizeCmb.getSelectedItem().toString();
            Beverage = beverageCmb.getSelectedItem().toString();
            //   c.setRegisteredBy(registeredBy);   

        }

        if (c instanceof CofftasticManager) {
            c = new CofftasticManager();

            //  cupSize = cupsizeCmb.getText(); /// GET WORKING ON WED
            //  Beverage = beverageCmb.getText(); /// GET WORKING ON WED
            c.setCupSize(cupSize);
            c.setBeverage(Beverage);
            c.setCustomer(Customer);
            ((CofftasticManager) c).setTransID(transID);
            ((CofftasticManager) c).setManagerType(managerType);

            cupSize = cupsizeCmb.getSelectedItem().toString();
            Beverage = beverageCmb.getSelectedItem().toString();
            managerType = manTypeCmb.getSelectedItem().toString();
            transID = Integer.parseInt(transidTf.getText());
            Customer = cusNameTf.getText();

        }

        aList.add(c);

        writeToFile();


    }//GEN-LAST:event_addBtnActionPerformed

    private void searchTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTIDActionPerformed
        // TODO add your handling code here:
        String searchName = JOptionPane.showInputDialog(null, "Enter Customer name");

        for (int i = 0; i < aList.size(); i++) {
            if (searchName.equalsIgnoreCase(aList.get(i).Customer)) {
                JOptionPane.showMessageDialog(null, aList.get(i).printDetails());
            }

        }


    }//GEN-LAST:event_searchTIDActionPerformed

    private void fsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsBtnActionPerformed
        // TODO add your handling code here:

        cusNameLbl.setVisible(true);
        cusNameTf.setVisible(true);
        transidLbl.setVisible(false);
        transidTf.setVisible(false);
        regbyTf.setVisible(true);
        regbyLbl.setVisible(true);
        beverageLbl.setVisible(true);
        beverageCmb.setVisible(true);
        cupsizeLbl.setVisible(true);
        cupsizeCmb.setVisible(true);
        addBtn.setVisible(true);
        displayBtn.setVisible(true);
        searchTID.setVisible(false);
        deleteBtn.setVisible(false);
        viewsavedBtn.setVisible(false);
        manTypeCmb.setVisible(false);
        manTypeLbl.setVisible(false);

        c = new CofftasticEmployee();

    }//GEN-LAST:event_fsBtnActionPerformed

    private void manBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manBtnActionPerformed
        // TODO add your handling code here:

        cusNameLbl.setVisible(true);
        cusNameTf.setVisible(true);
        transidLbl.setVisible(true);
        transidTf.setVisible(true);
        regbyTf.setVisible(false);
        regbyLbl.setVisible(false);
        beverageLbl.setVisible(true);
        beverageCmb.setVisible(true);
        cupsizeLbl.setVisible(true);
        cupsizeCmb.setVisible(true);
        addBtn.setVisible(true);
        displayBtn.setVisible(true);
        searchTID.setVisible(true);
        deleteBtn.setVisible(true);
        viewsavedBtn.setVisible(true);
        manTypeCmb.setVisible(true);
        manTypeLbl.setVisible(true);

        c = new CofftasticManager();

    }//GEN-LAST:event_manBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, aList.get(i).printDetails());
        }


    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String cusName = cusNameTf.getText();
        
        Cofftastic c;
        coffcount = aList.size();
        if (cusName.equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter Customer Name");
        } 
        else 
        {
            for (int i = 0; i < coffcount; i++) {
               
                c = aList.get(i);
                if (cusName.equals(c.getCustomer())) 
                {

                    aList.remove(i);

                    JOptionPane.showMessageDialog(null, c.getCustomer() + " Has been Deleted "
                            + "There are" + coffcount + "Customers in the database");
                    break;
                }
            }
        }
        if (coffcount == 0) {
            JOptionPane.showMessageDialog(null, "There is zero Customers in the database");
        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void cupsizeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupsizeCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupsizeCmbActionPerformed

    private void regbyTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbyTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regbyTfActionPerformed

    private void viewsavedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsavedBtnActionPerformed
        // TODO add your handling code here:

        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            ArrayList<Cofftastic> aList;
            aList = (ArrayList<Cofftastic>) oStream.readObject();
            for (Cofftastic c : aList) {
                JOptionPane.showMessageDialog(null, c.printDetails());
            }
            oStream.close();

        } catch (IOException e) {
            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewsavedBtnActionPerformed

    private void commentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentBtnActionPerformed
        // TODO add your handling code here:
        new CommentGUI().setVisible(true);
    }//GEN-LAST:event_commentBtnActionPerformed

    private void manTypeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manTypeCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manTypeCmbActionPerformed

    public void writeToFile() {
        

        try {
            File f = new File ("output.data");
            FileOutputStream os = new FileOutputStream (f);
            ObjectOutputStream outputStream = new ObjectOutputStream (os);

            outputStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "File Saved Successfully");

            outputStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CofftasticTillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CofftasticTillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CofftasticTillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CofftasticTillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CofftasticTillGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> beverageCmb;
    private javax.swing.JLabel beverageLbl;
    private javax.swing.JButton commentBtn;
    private javax.swing.JComboBox<String> cupsizeCmb;
    private javax.swing.JLabel cupsizeLbl;
    private javax.swing.JLabel cusNameLbl;
    private javax.swing.JTextField cusNameTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton fsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manBtn;
    private javax.swing.JComboBox<String> manTypeCmb;
    private javax.swing.JLabel manTypeLbl;
    private javax.swing.JLabel regbyLbl;
    private javax.swing.JTextField regbyTf;
    private javax.swing.JButton searchTID;
    private javax.swing.JLabel transidLbl;
    private javax.swing.JTextField transidTf;
    private javax.swing.JButton viewsavedBtn;
    // End of variables declaration//GEN-END:variables
}
